# Generated by Django 4.0.4 on 2022-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('path', models.CharField(db_column='Path', max_length=255)),
            ],
            options={
                'db_table': 'chart',
                'managed': False,
            },
        ),
    ]
